# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c7cfb754c33a13a51a147d0ecb8eea7762e914128234e3ddf766e568fa17e356fe34606ddd489e2c53946335a5ed6b51ba1ee230fc09659e7b90139af267326a

test:
  secret_key_base: b4499799c1ac20f423db70f011f7f48d234c5aecbaffbc5f4aca37b7634ca53cbf246b138e157f4494f68303f7582083377d27ec36cef9fe8ec0b9412dd8313a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
